/*
 * User API
 * API documentation for user management.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.UserDto;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserApi
 */
@Disabled
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Create a new user
     *
     * Creates a new user with the provided information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createUserTest() throws ApiException {
        UserDto userDto = null;
        UserDto response = api.createUser(userDto);
        // TODO: test validations
    }

    /**
     * Delete user by ID
     *
     * Deletes a user by their unique ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteUserTest() throws ApiException {
        Object id = null;
        api.deleteUser(id);
        // TODO: test validations
    }

    /**
     * Get all users
     *
     * Retrieves a list of all users.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllUsersTest() throws ApiException {
        Object response = api.getAllUsers();
        // TODO: test validations
    }

    /**
     * Get user by ID
     *
     * Retrieves a user by their unique ID.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserByIdTest() throws ApiException {
        Object id = null;
        UserDto response = api.getUserById(id);
        // TODO: test validations
    }

    /**
     * Update user by ID
     *
     * Updates an existing user with the provided information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateUserTest() throws ApiException {
        Object id = null;
        UserDto userDto = null;
        UserDto response = api.updateUser(id, userDto);
        // TODO: test validations
    }

}
