openapi: 3.0.3
info:
  title: Product API
  version: "1.0"
  description: API to retrieve product details.
paths:
  /api/product:
    get:
      summary: Get all products
      description: Retrieve a list of all available products.
      operationId: getAll
      tags:
        - Product
      responses:
        "200":
          description: A list of products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
components:
  schemas:
    ProductDto:
      $ref: './openapi-v3.yaml#/components/schemas/ProductDto'
    SampleDto:
      $ref: './openapi-v3.yaml#/components/schemas/SampleDto'